/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding.workspace'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding.team'
import { Route as OnboardingEmailAccountsRouteImport } from './routes/onboarding.email-accounts'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding.done'
import { Route as OnboardingBusinessTypeRouteImport } from './routes/onboarding.business-type'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email.unsubscribe'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppSearchRouteImport } from './routes/_authenticated/app.search'
import { Route as AuthenticatedAppRadarRouteImport } from './routes/_authenticated/app.radar'
import { Route as AuthenticatedAppPipelineRouteImport } from './routes/_authenticated/app.pipeline'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMemoryRouteImport } from './routes/_authenticated/app.memory'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppEmailSourcesRouteImport } from './routes/_authenticated/app.email-sources'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppIntegrationsIndexRouteImport } from './routes/_authenticated/app.integrations.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound.email'
import { Route as ApiPublicEmailUnsubscribeRouteImport } from './routes/api/public/email.unsubscribe'
import { Route as ApiPublicCronSyncRouteImport } from './routes/api/public/cron.sync'
import { Route as ApiPublicCronEscalateRouteImport } from './routes/api/public/cron.escalate'
import { Route as ApiPublicCronDailyDigestRouteImport } from './routes/api/public/cron.daily-digest'
import { Route as AuthenticatedAppSettingsAccountRouteImport } from './routes/_authenticated/app.settings.account'
import { Route as AuthenticatedAppNotificationsSettingsRouteImport } from './routes/_authenticated/app.notifications.settings'
import { Route as AuthenticatedAppIntegrationsWebhooksRouteImport } from './routes/_authenticated/app.integrations.webhooks'
import { Route as AuthenticatedAppIntegrationsConnectedRouteImport } from './routes/_authenticated/app.integrations.connected'
import { Route as AuthenticatedAppIntegrationsProviderIdRouteImport } from './routes/_authenticated/app.integrations.$providerId'
import { Route as ApiPublicOauthGmailCallbackRouteImport } from './routes/api/public/oauth.gmail.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingEmailAccountsRoute = OnboardingEmailAccountsRouteImport.update({
  id: '/email-accounts',
  path: '/email-accounts',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBusinessTypeRoute = OnboardingBusinessTypeRouteImport.update({
  id: '/business-type',
  path: '/business-type',
  getParentRoute: () => OnboardingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSearchRoute = AuthenticatedAppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRadarRoute = AuthenticatedAppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPipelineRoute =
  AuthenticatedAppPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMemoryRoute = AuthenticatedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEmailSourcesRoute =
  AuthenticatedAppEmailSourcesRouteImport.update({
    id: '/email-sources',
    path: '/email-sources',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIntegrationsIndexRoute =
  AuthenticatedAppIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound/email',
  path: '/api/public/inbound/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailUnsubscribeRoute =
  ApiPublicEmailUnsubscribeRouteImport.update({
    id: '/api/public/email/unsubscribe',
    path: '/api/public/email/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncRoute = ApiPublicCronSyncRouteImport.update({
  id: '/api/public/cron/sync',
  path: '/api/public/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEscalateRoute = ApiPublicCronEscalateRouteImport.update({
  id: '/api/public/cron/escalate',
  path: '/api/public/cron/escalate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyDigestRoute =
  ApiPublicCronDailyDigestRouteImport.update({
    id: '/api/public/cron/daily-digest',
    path: '/api/public/cron/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSettingsAccountRoute =
  AuthenticatedAppSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsSettingsRoute =
  AuthenticatedAppNotificationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppNotificationsRoute,
  } as any)
const AuthenticatedAppIntegrationsWebhooksRoute =
  AuthenticatedAppIntegrationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppIntegrationsConnectedRoute =
  AuthenticatedAppIntegrationsConnectedRouteImport.update({
    id: '/connected',
    path: '/connected',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const AuthenticatedAppIntegrationsProviderIdRoute =
  AuthenticatedAppIntegrationsProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AuthenticatedAppIntegrationsRoute,
  } as any)
const ApiPublicOauthGmailCallbackRoute =
  ApiPublicOauthGmailCallbackRouteImport.update({
    id: '/api/public/oauth/gmail/callback',
    path: '/api/public/oauth/gmail/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/email-accounts': typeof OnboardingEmailAccountsRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/email-sources': typeof AuthenticatedAppEmailSourcesRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRouteWithChildren
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRouteWithChildren
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/integrations/$providerId': typeof AuthenticatedAppIntegrationsProviderIdRoute
  '/app/integrations/connected': typeof AuthenticatedAppIntegrationsConnectedRoute
  '/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/app/notifications/settings': typeof AuthenticatedAppNotificationsSettingsRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/escalate': typeof ApiPublicCronEscalateRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/inbound/email': typeof ApiPublicInboundEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/api/public/oauth/gmail/callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/email-accounts': typeof OnboardingEmailAccountsRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/email-sources': typeof AuthenticatedAppEmailSourcesRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRouteWithChildren
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/integrations/$providerId': typeof AuthenticatedAppIntegrationsProviderIdRoute
  '/app/integrations/connected': typeof AuthenticatedAppIntegrationsConnectedRoute
  '/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/app/notifications/settings': typeof AuthenticatedAppNotificationsSettingsRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/escalate': typeof ApiPublicCronEscalateRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/inbound/email': typeof ApiPublicInboundEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsIndexRoute
  '/api/public/oauth/gmail/callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/business-type': typeof OnboardingBusinessTypeRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/email-accounts': typeof OnboardingEmailAccountsRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/app/email-sources': typeof AuthenticatedAppEmailSourcesRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRouteWithChildren
  '/_authenticated/app/memory': typeof AuthenticatedAppMemoryRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRouteWithChildren
  '/_authenticated/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/_authenticated/app/radar': typeof AuthenticatedAppRadarRoute
  '/_authenticated/app/search': typeof AuthenticatedAppSearchRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/integrations/$providerId': typeof AuthenticatedAppIntegrationsProviderIdRoute
  '/_authenticated/app/integrations/connected': typeof AuthenticatedAppIntegrationsConnectedRoute
  '/_authenticated/app/integrations/webhooks': typeof AuthenticatedAppIntegrationsWebhooksRoute
  '/_authenticated/app/notifications/settings': typeof AuthenticatedAppNotificationsSettingsRoute
  '/_authenticated/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/cron/daily-digest': typeof ApiPublicCronDailyDigestRoute
  '/api/public/cron/escalate': typeof ApiPublicCronEscalateRoute
  '/api/public/cron/sync': typeof ApiPublicCronSyncRoute
  '/api/public/email/unsubscribe': typeof ApiPublicEmailUnsubscribeRoute
  '/api/public/inbound/email': typeof ApiPublicInboundEmailRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/integrations/': typeof AuthenticatedAppIntegrationsIndexRoute
  '/api/public/oauth/gmail/callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/onboarding/business-type'
    | '/onboarding/done'
    | '/onboarding/email-accounts'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/app/analytics'
    | '/app/crm'
    | '/app/email-sources'
    | '/app/help'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/memory'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/radar'
    | '/app/search'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
    | '/app/integrations/$providerId'
    | '/app/integrations/connected'
    | '/app/integrations/webhooks'
    | '/app/notifications/settings'
    | '/app/settings/account'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/escalate'
    | '/api/public/cron/sync'
    | '/api/public/email/unsubscribe'
    | '/api/public/inbound/email'
    | '/lovable/email/queue/process'
    | '/app/integrations/'
    | '/api/public/oauth/gmail/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/onboarding/business-type'
    | '/onboarding/done'
    | '/onboarding/email-accounts'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding'
    | '/app/analytics'
    | '/app/crm'
    | '/app/email-sources'
    | '/app/help'
    | '/app/inbox'
    | '/app/memory'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/radar'
    | '/app/search'
    | '/app/tasks'
    | '/app/team'
    | '/app'
    | '/app/integrations/$providerId'
    | '/app/integrations/connected'
    | '/app/integrations/webhooks'
    | '/app/notifications/settings'
    | '/app/settings/account'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/escalate'
    | '/api/public/cron/sync'
    | '/api/public/email/unsubscribe'
    | '/api/public/inbound/email'
    | '/lovable/email/queue/process'
    | '/app/integrations'
    | '/api/public/oauth/gmail/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/_authenticated/app'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/onboarding/business-type'
    | '/onboarding/done'
    | '/onboarding/email-accounts'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/onboarding/'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/email-sources'
    | '/_authenticated/app/help'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/memory'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/pipeline'
    | '/_authenticated/app/radar'
    | '/_authenticated/app/search'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/team'
    | '/_authenticated/app/'
    | '/_authenticated/app/integrations/$providerId'
    | '/_authenticated/app/integrations/connected'
    | '/_authenticated/app/integrations/webhooks'
    | '/_authenticated/app/notifications/settings'
    | '/_authenticated/app/settings/account'
    | '/api/public/cron/daily-digest'
    | '/api/public/cron/escalate'
    | '/api/public/cron/sync'
    | '/api/public/email/unsubscribe'
    | '/api/public/inbound/email'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/integrations/'
    | '/api/public/oauth/gmail/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicCronDailyDigestRoute: typeof ApiPublicCronDailyDigestRoute
  ApiPublicCronEscalateRoute: typeof ApiPublicCronEscalateRoute
  ApiPublicCronSyncRoute: typeof ApiPublicCronSyncRoute
  ApiPublicEmailUnsubscribeRoute: typeof ApiPublicEmailUnsubscribeRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicOauthGmailCallbackRoute: typeof ApiPublicOauthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/email-accounts': {
      id: '/onboarding/email-accounts'
      path: '/email-accounts'
      fullPath: '/onboarding/email-accounts'
      preLoaderRoute: typeof OnboardingEmailAccountsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/business-type': {
      id: '/onboarding/business-type'
      path: '/business-type'
      fullPath: '/onboarding/business-type'
      preLoaderRoute: typeof OnboardingBusinessTypeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/search': {
      id: '/_authenticated/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AuthenticatedAppSearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/radar': {
      id: '/_authenticated/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AuthenticatedAppRadarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline': {
      id: '/_authenticated/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AuthenticatedAppPipelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory': {
      id: '/_authenticated/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AuthenticatedAppMemoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/email-sources': {
      id: '/_authenticated/app/email-sources'
      path: '/email-sources'
      fullPath: '/app/email-sources'
      preLoaderRoute: typeof AuthenticatedAppEmailSourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations/': {
      id: '/_authenticated/app/integrations/'
      path: '/'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound/email': {
      id: '/api/public/inbound/email'
      path: '/api/public/inbound/email'
      fullPath: '/api/public/inbound/email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/unsubscribe': {
      id: '/api/public/email/unsubscribe'
      path: '/api/public/email/unsubscribe'
      fullPath: '/api/public/email/unsubscribe'
      preLoaderRoute: typeof ApiPublicEmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync': {
      id: '/api/public/cron/sync'
      path: '/api/public/cron/sync'
      fullPath: '/api/public/cron/sync'
      preLoaderRoute: typeof ApiPublicCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/escalate': {
      id: '/api/public/cron/escalate'
      path: '/api/public/cron/escalate'
      fullPath: '/api/public/cron/escalate'
      preLoaderRoute: typeof ApiPublicCronEscalateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-digest': {
      id: '/api/public/cron/daily-digest'
      path: '/api/public/cron/daily-digest'
      fullPath: '/api/public/cron/daily-digest'
      preLoaderRoute: typeof ApiPublicCronDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings/account': {
      id: '/_authenticated/app/settings/account'
      path: '/settings/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications/settings': {
      id: '/_authenticated/app/notifications/settings'
      path: '/settings'
      fullPath: '/app/notifications/settings'
      preLoaderRoute: typeof AuthenticatedAppNotificationsSettingsRouteImport
      parentRoute: typeof AuthenticatedAppNotificationsRoute
    }
    '/_authenticated/app/integrations/webhooks': {
      id: '/_authenticated/app/integrations/webhooks'
      path: '/webhooks'
      fullPath: '/app/integrations/webhooks'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsWebhooksRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/integrations/connected': {
      id: '/_authenticated/app/integrations/connected'
      path: '/connected'
      fullPath: '/app/integrations/connected'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsConnectedRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/_authenticated/app/integrations/$providerId': {
      id: '/_authenticated/app/integrations/$providerId'
      path: '/$providerId'
      fullPath: '/app/integrations/$providerId'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsProviderIdRouteImport
      parentRoute: typeof AuthenticatedAppIntegrationsRoute
    }
    '/api/public/oauth/gmail/callback': {
      id: '/api/public/oauth/gmail/callback'
      path: '/api/public/oauth/gmail/callback'
      fullPath: '/api/public/oauth/gmail/callback'
      preLoaderRoute: typeof ApiPublicOauthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppIntegrationsRouteChildren {
  AuthenticatedAppIntegrationsProviderIdRoute: typeof AuthenticatedAppIntegrationsProviderIdRoute
  AuthenticatedAppIntegrationsConnectedRoute: typeof AuthenticatedAppIntegrationsConnectedRoute
  AuthenticatedAppIntegrationsWebhooksRoute: typeof AuthenticatedAppIntegrationsWebhooksRoute
  AuthenticatedAppIntegrationsIndexRoute: typeof AuthenticatedAppIntegrationsIndexRoute
}

const AuthenticatedAppIntegrationsRouteChildren: AuthenticatedAppIntegrationsRouteChildren =
  {
    AuthenticatedAppIntegrationsProviderIdRoute:
      AuthenticatedAppIntegrationsProviderIdRoute,
    AuthenticatedAppIntegrationsConnectedRoute:
      AuthenticatedAppIntegrationsConnectedRoute,
    AuthenticatedAppIntegrationsWebhooksRoute:
      AuthenticatedAppIntegrationsWebhooksRoute,
    AuthenticatedAppIntegrationsIndexRoute:
      AuthenticatedAppIntegrationsIndexRoute,
  }

const AuthenticatedAppIntegrationsRouteWithChildren =
  AuthenticatedAppIntegrationsRoute._addFileChildren(
    AuthenticatedAppIntegrationsRouteChildren,
  )

interface AuthenticatedAppNotificationsRouteChildren {
  AuthenticatedAppNotificationsSettingsRoute: typeof AuthenticatedAppNotificationsSettingsRoute
}

const AuthenticatedAppNotificationsRouteChildren: AuthenticatedAppNotificationsRouteChildren =
  {
    AuthenticatedAppNotificationsSettingsRoute:
      AuthenticatedAppNotificationsSettingsRoute,
  }

const AuthenticatedAppNotificationsRouteWithChildren =
  AuthenticatedAppNotificationsRoute._addFileChildren(
    AuthenticatedAppNotificationsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppEmailSourcesRoute: typeof AuthenticatedAppEmailSourcesRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRouteWithChildren
  AuthenticatedAppMemoryRoute: typeof AuthenticatedAppMemoryRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRouteWithChildren
  AuthenticatedAppPipelineRoute: typeof AuthenticatedAppPipelineRoute
  AuthenticatedAppRadarRoute: typeof AuthenticatedAppRadarRoute
  AuthenticatedAppSearchRoute: typeof AuthenticatedAppSearchRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSettingsAccountRoute: typeof AuthenticatedAppSettingsAccountRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppEmailSourcesRoute: AuthenticatedAppEmailSourcesRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppIntegrationsRoute:
    AuthenticatedAppIntegrationsRouteWithChildren,
  AuthenticatedAppMemoryRoute: AuthenticatedAppMemoryRoute,
  AuthenticatedAppNotificationsRoute:
    AuthenticatedAppNotificationsRouteWithChildren,
  AuthenticatedAppPipelineRoute: AuthenticatedAppPipelineRoute,
  AuthenticatedAppRadarRoute: AuthenticatedAppRadarRoute,
  AuthenticatedAppSearchRoute: AuthenticatedAppSearchRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSettingsAccountRoute: AuthenticatedAppSettingsAccountRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OnboardingRouteChildren {
  OnboardingBusinessTypeRoute: typeof OnboardingBusinessTypeRoute
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingEmailAccountsRoute: typeof OnboardingEmailAccountsRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBusinessTypeRoute: OnboardingBusinessTypeRoute,
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingEmailAccountsRoute: OnboardingEmailAccountsRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicCronDailyDigestRoute: ApiPublicCronDailyDigestRoute,
  ApiPublicCronEscalateRoute: ApiPublicCronEscalateRoute,
  ApiPublicCronSyncRoute: ApiPublicCronSyncRoute,
  ApiPublicEmailUnsubscribeRoute: ApiPublicEmailUnsubscribeRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicOauthGmailCallbackRoute: ApiPublicOauthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
